# Generated by Django 5.1.7 on 2025-03-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nome de usuário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
        ),
    ]
