# Generated by Django 5.1.7 on 2025-03-31 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('qtd', models.IntegerField(default=1, verbose_name='Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character', verbose_name='Personagem')),
            ],
        ),
    ]
