# Generated by Django 5.1.7 on 2025-03-31 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('em andamento', 'Em Andamento'), ('vitória', 'Vitória'), ('derrota', 'Derrota')], default='em andamento', max_length=50, verbose_name='Status')),
                ('inimigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batalhas_como_inimigo', to='characters.character', verbose_name='Inimigo')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character', verbose_name='Personagem')),
            ],
        ),
    ]
