# Generated by Django 5.1.7 on 2025-03-31 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Ocupation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('benefits', models.TextField(verbose_name='Benefícios')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('race', models.CharField(max_length=100, verbose_name='Raça')),
                ('birth_region', models.CharField(max_length=100, verbose_name='Região de Nascimento')),
                ('level', models.IntegerField(default=1, verbose_name='Nível')),
                ('experience', models.IntegerField(default=0, verbose_name='Experiência')),
                ('health', models.IntegerField(default=100, verbose_name='Vida')),
                ('mana', models.IntegerField(default=100, verbose_name='Mana')),
                ('blessing', models.CharField(blank=True, max_length=100, null=True, verbose_name='Benção')),
                ('sprite', models.ImageField(blank=True, null=True, upload_to='sprites/', verbose_name='Sprite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authent.user', verbose_name='Usuário')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.classe', verbose_name='Classe')),
            ],
        ),
    ]
