# Generated by Django 5.1.7 on 2025-03-31 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('itens_disponiveis', models.ManyToManyField(blank=True, to='inventory.item', verbose_name='Itens Disponíveis')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('cidade', 'Cidade'), ('masmorra', 'Masmorra'), ('floresta', 'Floresta'), ('montanha', 'Montanha'), ('deserto', 'Deserto'), ('vilarejo', 'Vilarejo')], default='cidade', max_length=50, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploration.regiao', verbose_name='Região')),
            ],
        ),
    ]
